//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_.Test_
{
    /// <summary>
    /// The DateAssert object provides functions to test JavaScript Date objects
    /// for a variety of cases.
    /// </summary>
    public partial class DateAssert
    {
        /// <summary>
        /// Asserts that a date's month, day, and year are equal to another date's.
        /// </summary>
        public void datesAreEqual(Y_.DataType_.Date expected, Y_.DataType_.Date actual, object message){}
        /// <summary>
        /// Asserts that a date's hour, minutes, and seconds are equal to another date's.
        /// </summary>
        public void timesAreEqual(Y_.DataType_.Date expected, Y_.DataType_.Date actual, object message){}
    }
}
