//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_.Test_
{
    /// <summary>
    /// UnexpectedValue is subclass of Error that is thrown whenever
    /// a value was unexpected in its scope. This typically means that a test
    /// was performed to determine that a value was *not* equal to a certain
    /// value.
    /// </summary>
    public partial class UnexpectedValue : AssertionError
    {
        /// <summary>
        /// Returns a fully formatted error for an assertion failure. This message
        /// provides information about the expected and actual values.
        /// </summary>
        public object getMessage(){return null;}
        /// <summary>
        /// The unexpected value.
        /// </summary>
        public object unexpected{get;set;}
    }
}
