// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.theme.classic
{
    /// <summary>
	/// <para>Windows classic color theme</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.theme.classic.Color", OmitOptionalParameters = true, Export = false)]
    public partial class Color 
    {
		#region Methods

		public Color() { throw new NotImplementedException(); }

		#endregion Methods
    }
}