//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_
{
    /// <summary>
    /// <p>Creates an ellipse shape with editable attributes.</p>
    /// <p>`Ellipse` instances can be created using the <a href="Graphic.html#method_addShape">`addShape`</a> method of the <a href="Graphic.html">`Graphic`</a> class.
    /// The method's `cfg` argument contains a `type` attribute. Assigning "ellipse" or `Y.Ellipse` to this attribute will create a `Ellipse` instance. Required attributes
    /// for instantiating a `Ellipse` are `type`, `width` and `height`. Optional attributes include:
    /// <ul>
    /// <li><a href="#attr_fill">fill</a></li>
    /// <li><a href="#attr_id">id</a></li>
    /// <li><a href="#attr_stroke">stroke</a></li>
    /// <li><a href="#attr_transform">transform</a></li>
    /// <li><a href="#attr_transformOrigin">transformOrigin</a></li>
    /// <li><a href="#attr_visible">visible</a></li>
    /// <li><a href="#attr_x">x</a></li>
    /// <li><a href="#attr_y">y</a></li>
    /// </ul>
    /// The below code creates an ellipse by defining the `type` attribute as "ellipse":</p>
    /// var myEllipse = myGraphic.addShape({
    /// type: "ellipse",
    /// width: 20,
    /// height: 10,
    /// fill: {
    /// color: "#9aa"
    /// },
    /// stroke: {
    /// weight: 1,
    /// color: "#000"
    /// }
    /// });
    /// Below, the same ellipse is created by defining the `type` attribute with a class reference:
    /// var myEllipse = myGraphic.addShape({
    /// type: Y.Ellipse,
    /// width: 20,
    /// height: 10,
    /// fill: {
    /// color: "#9aa"
    /// },
    /// stroke: {
    /// weight: 1,
    /// color: "#000"
    /// }
    /// });
    /// <p>`Ellipse` has the following implementations based on browser capability.
    /// <ul>
    /// <li><a href="SVGEllipse.html">`SVGEllipse`</a></li>
    /// <li><a href="VMLEllipse.html">`VMLEllipse`</a></li>
    /// <li><a href="CanvasEllipse.html">`CanvasEllipse`</a></li>
    /// </ul>
    /// It is not necessary to interact with these classes directly. `Ellipse` will point to the appropriate implemention.</p>
    /// </summary>
    public partial class Ellipse : Shape
    {
    }
}
