//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_
{
    /// <summary>
    /// `Y.File` serves as an alias for either <a href="FileFlash.html">`Y.FileFlash`</a>
    /// or <a href="FileHTML5.html">`Y.FileHTML5`</a>, depending on the feature set available
    /// in a specific browser.
    /// </summary>
    public partial class File
    {
    }
}
