//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_
{
    /// <summary>
    /// Contains methods for displaying items vertically in a legend.
    /// </summary>
    public partial class VerticalLegendLayout
    {
        /// <summary>
        /// Positions the legend in a chart and returns the properties of the legend to be used in the
        /// chart's layout algorithm.
        /// </summary>
        protected object _getLayoutDimensions(){return null;}
        /// <summary>
        /// Displays items vertically in a legend.
        /// </summary>
        protected void _positionLegendItems(Y_.Array items, Y_.DataType_.Number maxWidth, Y_.DataType_.Number maxHeight, Y_.DataType_.Number totalWidth, Y_.DataType_.Number totalHeight, Y_.DataType_.Number padding, Y_.DataType_.Number horizontalGap, Y_.DataType_.Number verticalGap, object hAlign, object vAlign){}
        /// <summary>
        /// Creates column and total height arrays used for displaying multiple columns of
        /// legend items based on the items, available height and verticalGap for the legend.
        /// </summary>
        protected void _setColumnArrays(Y_.Array items, Y_.DataType_.Number limit, Y_.DataType_.Number verticalGap){}
        /// <summary>
        /// Destructor implementation for the CartesianChart class. Calls destroy on all axes, series, legend (if available) and the Graph instance.
        /// Removes the tooltip and overlay HTML elements.
        /// </summary>
        protected void destructor(){}
        /// <summary>
        /// Returns the starting y-coordinate for a column of legend items.
        /// </summary>
        protected Y_.DataType_.Number getStartPoint(Y_.DataType_.Number h, Y_.DataType_.Number totalHeight, object align, object padding){return null;}
    }
}
