// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.module.util
{
    /// <summary>
	/// <para>Utility for checking the type of a variable.
	/// It adds a type key static to q and offers the given method.</para>
	/// <code>
	/// q.type.get("abc"); // return "String" e.g.
	/// </code>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.module.util.Type", OmitOptionalParameters = true, Export = false)]
    public partial class Type 
    {
		#region Methods

		public Type() { throw new NotImplementedException(); }

		#endregion Methods
    }
}