//***************************************************
//* This file was generated by tool
//* SharpKit
//* At: 29/08/2012 03:59:42 p.m.
//***************************************************
using SharpKit.JavaScript;
namespace Ext
{
    #region WindowManager
    /// <inheritdocs />
    /// <summary>
    /// <p>The default global floating Component group that is available automatically.</p>
    /// <p>This manages instances of floating Components which were rendered programatically without
    /// being added to a <see cref="Ext.container.Container">Container</see>, and for floating Components
    /// which were added into non-floating Containers.</p>
    /// <p><em>Floating</em> Containers create their own instance of ZIndexManager, and floating Components
    /// added at any depth below there are managed by that ZIndexManager.</p>
    /// </summary>
    [JsType(JsMode.Prototype, Export=false, OmitOptionalParameters=true)]
    public partial class WindowManager : ZIndexManager
    {
        /// <summary>
        /// Defaults to: <c>&quot;Ext.Base&quot;</c>
        /// </summary>
        [JsProperty(Name="$className")]
        private static JsString @className{get;set;}
        /// <summary>
        /// Defaults to: <c>{}</c>
        /// </summary>
        private static JsObject configMap{get;set;}
        /// <summary>
        /// Defaults to: <c>[]</c>
        /// </summary>
        private static JsArray initConfigList{get;set;}
        /// <summary>
        /// Defaults to: <c>{}</c>
        /// </summary>
        private static JsObject initConfigMap{get;set;}
        /// <summary>
        /// Defaults to: <c>true</c>
        /// </summary>
        private static bool isInstance{get;set;}
        /// <summary>
        /// Get the reference to the current class from which this object was instantiated. Unlike statics,
        /// this.self is scope-dependent and it's meant to be used for dynamic inheritance. See statics
        /// for a detailed comparison
        /// <code><see cref="Ext.ExtContext.define">Ext.define</see>('My.Cat', {
        /// statics: {
        /// speciesName: 'Cat' // My.Cat.speciesName = 'Cat'
        /// },
        /// constructor: function() {
        /// alert(this.self.speciesName); // dependent on 'this'
        /// },
        /// clone: function() {
        /// return new this.self();
        /// }
        /// });
        /// <see cref="Ext.ExtContext.define">Ext.define</see>('My.SnowLeopard', {
        /// extend: 'My.Cat',
        /// statics: {
        /// speciesName: 'Snow Leopard'         // My.SnowLeopard.speciesName = 'Snow Leopard'
        /// }
        /// });
        /// var cat = new My.Cat();                     // alerts 'Cat'
        /// var snowLeopard = new My.SnowLeopard();     // alerts 'Snow Leopard'
        /// var clone = snowLeopard.clone();
        /// alert(<see cref="Ext.ExtContext.getClassName">Ext.getClassName</see>(clone));             // alerts 'My.SnowLeopard'
        /// </code>
        /// </summary>
        protected static Class self{get;set;}
        /// <summary>
        /// Brings the specified Component to the front of any other active Components in this ZIndexManager.
        /// </summary>
        /// <param name="comp"><p>The id of the Component or a <see cref="Ext.Component">Ext.Component</see> instance</p>
        /// </param>
        /// <returns>
        /// <span><see cref="bool">Boolean</see></span><div><p>True if the dialog was brought to the front, else false
        /// if it was already in front</p>
        /// </div>
        /// </returns>
        public static bool bringToFront(object comp){return false;}
        /// <summary>
        /// Call the original method that was previously overridden with override
        /// <code><see cref="Ext.ExtContext.define">Ext.define</see>('My.Cat', {
        /// constructor: function() {
        /// alert("I'm a cat!");
        /// }
        /// });
        /// My.Cat.override({
        /// constructor: function() {
        /// alert("I'm going to be a cat!");
        /// this.callOverridden();
        /// alert("Meeeeoooowwww");
        /// }
        /// });
        /// var kitty = new My.Cat(); // alerts "I'm going to be a cat!"
        /// // alerts "I'm a cat!"
        /// // alerts "Meeeeoooowwww"
        /// </code>
        /// <p>This method has been <strong>deprecated</strong> </p>
        /// <p>as of 4.1. Use <see cref="Ext.Base.callParent">callParent</see> instead.</p>
        /// </summary>
        /// <param name="args"><p>The arguments, either an array or the <c>arguments</c> object
        /// from the current method, for example: <c>this.callOverridden(arguments)</c></p>
        /// </param>
        /// <returns>
        /// <span><see cref="Object">Object</see></span><div><p>Returns the result of calling the overridden method</p>
        /// </div>
        /// </returns>
        protected static object callOverridden(object args=null){return null;}
        /// <summary>
        /// Call the "parent" method of the current method. That is the method previously
        /// overridden by derivation or by an override (see Ext.define).
        /// <code> <see cref="Ext.ExtContext.define">Ext.define</see>('My.Base', {
        /// constructor: function (x) {
        /// this.x = x;
        /// },
        /// statics: {
        /// method: function (x) {
        /// return x;
        /// }
        /// }
        /// });
        /// <see cref="Ext.ExtContext.define">Ext.define</see>('My.Derived', {
        /// extend: 'My.Base',
        /// constructor: function () {
        /// this.callParent([21]);
        /// }
        /// });
        /// var obj = new My.Derived();
        /// alert(obj.x);  // alerts 21
        /// </code>
        /// This can be used with an override as follows:
        /// <code> <see cref="Ext.ExtContext.define">Ext.define</see>('My.DerivedOverride', {
        /// override: 'My.Derived',
        /// constructor: function (x) {
        /// this.callParent([x*2]); // calls original My.Derived constructor
        /// }
        /// });
        /// var obj = new My.Derived();
        /// alert(obj.x);  // now alerts 42
        /// </code>
        /// This also works with static methods.
        /// <code> <see cref="Ext.ExtContext.define">Ext.define</see>('My.Derived2', {
        /// extend: 'My.Base',
        /// statics: {
        /// method: function (x) {
        /// return this.callParent([x*2]); // calls My.Base.method
        /// }
        /// }
        /// });
        /// alert(My.Base.method(10);     // alerts 10
        /// alert(My.Derived2.method(10); // alerts 20
        /// </code>
        /// Lastly, it also works with overridden static methods.
        /// <code> <see cref="Ext.ExtContext.define">Ext.define</see>('My.Derived2Override', {
        /// override: 'My.Derived2',
        /// statics: {
        /// method: function (x) {
        /// return this.callParent([x*2]); // calls My.Derived2.method
        /// }
        /// }
        /// });
        /// alert(My.Derived2.method(10); // now alerts 40
        /// </code>
        /// </summary>
        /// <param name="args"><p>The arguments, either an array or the <c>arguments</c> object
        /// from the current method, for example: <c>this.callParent(arguments)</c></p>
        /// </param>
        /// <returns>
        /// <span><see cref="Object">Object</see></span><div><p>Returns the result of calling the parent method</p>
        /// </div>
        /// </returns>
        protected static object callParent(object args=null){return null;}
        /// <summary>
        /// </summary>
        private static void configClass(){}
        /// <summary>
        /// Overrides: <see cref="Ext.AbstractComponent.destroy">Ext.AbstractComponent.destroy</see>, <see cref="Ext.AbstractPlugin.destroy">Ext.AbstractPlugin.destroy</see>, <see cref="Ext.layout.Layout.destroy">Ext.layout.Layout.destroy</see>
        /// </summary>
        private static void destroy(){}
        /// <summary>
        /// Executes the specified function once for every Component in this ZIndexManager, passing each
        /// Component as the only parameter. Returning false from the function will stop the iteration.
        /// </summary>
        /// <param name="fn"><p>The function to execute for each item</p>
        /// </param>
        /// <param name="scope"><p>The scope (this reference) in which the function
        /// is executed. Defaults to the current Component in the iteration.</p>
        /// </param>
        public static void each(System.Delegate fn, object scope=null){}
        /// <summary>
        /// Executes the specified function once for every Component in this ZIndexManager, passing each
        /// Component as the only parameter. Returning false from the function will stop the iteration.
        /// The components are passed to the function starting at the bottom and proceeding to the top.
        /// </summary>
        /// <param name="fn"><p>The function to execute for each item</p>
        /// </param>
        /// <param name="scope"><p>The scope (this reference) in which the function
        /// is executed. Defaults to the current Component in the iteration.</p>
        /// </param>
        public static void eachBottomUp(System.Delegate fn, object scope=null){}
        /// <summary>
        /// Executes the specified function once for every Component in this ZIndexManager, passing each
        /// Component as the only parameter. Returning false from the function will stop the iteration.
        /// The components are passed to the function starting at the top and proceeding to the bottom.
        /// </summary>
        /// <param name="fn"><p>The function to execute for each item</p>
        /// </param>
        /// <param name="scope"><p>The scope (this reference) in which the function
        /// is executed. Defaults to the current Component in the iteration.</p>
        /// </param>
        public static void eachTopDown(System.Delegate fn, object scope=null){}
        /// <summary>
        /// Gets a registered Component by id.
        /// </summary>
        /// <param name="id"><p>The id of the Component or a <see cref="Ext.Component">Ext.Component</see> instance</p>
        /// </param>
        /// <returns>
        /// <span><see cref="Ext.Component">Ext.Component</see></span><div>
        /// </div>
        /// </returns>
        public static Ext.Component get(object id){return null;}
        /// <summary>
        /// Gets the currently-active Component in this ZIndexManager.
        /// </summary>
        /// <returns>
        /// <span><see cref="Ext.Component">Ext.Component</see></span><div><p>The active Component</p>
        /// </div>
        /// </returns>
        public static Ext.Component getActive(){return null;}
        /// <summary>
        /// Returns zero or more Components in this ZIndexManager using the custom search function passed to this method.
        /// The function should accept a single Ext.Component reference as its only argument and should
        /// return true if the Component matches the search criteria, otherwise it should return false.
        /// </summary>
        /// <param name="fn"><p>The search function</p>
        /// </param>
        /// <param name="scope"><p>The scope (this reference) in which the function is executed.
        /// Defaults to the Component being tested. That gets passed to the function if not specified.</p>
        /// </param>
        /// <returns>
        /// <span><see cref="Array">Array</see></span><div><p>An array of zero or more matching windows</p>
        /// </div>
        /// </returns>
        public static JsArray getBy(System.Delegate fn, object scope=null){return null;}
        /// <summary>
        /// Parameters<li><span>name</span> : <see cref="Object">Object</see><div>
        /// </div></li>
        /// </summary>
        /// <param name="name">
        /// </param>
        private static void getConfig(object name){}
        /// <summary>
        /// Returns the initial configuration passed to constructor when instantiating
        /// this class.
        /// </summary>
        /// <param name="name"><p>Name of the config option to return.</p>
        /// </param>
        /// <returns>
        /// <span><see cref="Object">Object</see>/Mixed</span><div><p>The full config object or a single config value
        /// when <c>name</c> parameter specified.</p>
        /// </div>
        /// </returns>
        public static object getInitialConfig(object name=null){return null;}
        /// <summary>
        /// Parameters<li><span>config</span> : <see cref="Object">Object</see><div>
        /// </div></li>
        /// </summary>
        /// <param name="config">
        /// </param>
        private static void hasConfig(object config){}
        /// <summary>
        /// Temporarily hides all currently visible managed Components. This is for when
        /// dragging a Window which may manage a set of floating descendants in its ZIndexManager;
        /// they should all be hidden just for the duration of the drag.
        /// </summary>
        private static void hide(){}
        /// <summary>
        /// Hides all Components managed by this ZIndexManager.
        /// </summary>
        public static void hideAll(){}
        /// <summary>
        /// Initialize configuration for this class. a typical example:
        /// <code><see cref="Ext.ExtContext.define">Ext.define</see>('My.awesome.Class', {
        /// // The default config
        /// config: {
        /// name: 'Awesome',
        /// isAwesome: true
        /// },
        /// constructor: function(config) {
        /// this.initConfig(config);
        /// }
        /// });
        /// var awesome = new My.awesome.Class({
        /// name: 'Super Awesome'
        /// });
        /// alert(awesome.getName()); // 'Super Awesome'
        /// </code>
        /// </summary>
        /// <param name="config">
        /// </param>
        /// <returns>
        /// <span><see cref="Ext.Base">Ext.Base</see></span><div><p>this</p>
        /// </div>
        /// </returns>
        protected static Ext.Base initConfig(object config){return null;}
        /// <summary>
        /// Parameters<li><span>names</span> : <see cref="Object">Object</see><div>
        /// </div></li><li><span>callback</span> : <see cref="Object">Object</see><div>
        /// </div></li><li><span>scope</span> : <see cref="Object">Object</see><div>
        /// </div></li>
        /// </summary>
        /// <param name="names">
        /// </param>
        /// <param name="callback">
        /// </param>
        /// <param name="scope">
        /// </param>
        private static void onConfigUpdate(object names, object callback, object scope){}
        /// <summary>
        /// Registers a floating Ext.Component with this ZIndexManager. This should not
        /// need to be called under normal circumstances. Floating Components (such as Windows,
        /// BoundLists and Menus) are automatically registered with a
        /// zIndexManager at render time.
        /// Where this may be useful is moving Windows between two ZIndexManagers. For example,
        /// to bring the <see cref="Ext.MessageBox">Ext.MessageBox</see> dialog under the same manager as the Desktop's
        /// ZIndexManager in the desktop sample app:
        /// <code>MyDesktop.getDesktop().getManager().register(<see cref="Ext.MessageBox">Ext.MessageBox</see>);
        /// </code>
        /// </summary>
        /// <param name="comp"><p>The Component to register.</p>
        /// </param>
        public static void register(Ext.Component comp){}
        /// <summary>
        /// Sends the specified Component to the back of other active Components in this ZIndexManager.
        /// </summary>
        /// <param name="comp"><p>The id of the Component or a <see cref="Ext.Component">Ext.Component</see> instance</p>
        /// </param>
        /// <returns>
        /// <span><see cref="Ext.Component">Ext.Component</see></span><div><p>The Component</p>
        /// </div>
        /// </returns>
        public static Ext.Component sendToBack(object comp){return null;}
        /// <summary>
        /// Parameters<li><span>config</span> : <see cref="Object">Object</see><div>
        /// </div></li><li><span>applyIfNotSet</span> : <see cref="Object">Object</see><div>
        /// </div></li>
        /// </summary>
        /// <param name="config">
        /// </param>
        /// <param name="applyIfNotSet">
        /// </param>
        private static void setConfig(object config, object applyIfNotSet){}
        /// <summary>
        /// Restores temporarily hidden managed Components to visibility.
        /// </summary>
        private static void show(){}
        /// <summary>
        /// Get the reference to the class from which this object was instantiated. Note that unlike self,
        /// this.statics() is scope-independent and it always returns the class from which it was called, regardless of what
        /// this points to during run-time
        /// <code><see cref="Ext.ExtContext.define">Ext.define</see>('My.Cat', {
        /// statics: {
        /// totalCreated: 0,
        /// speciesName: 'Cat' // My.Cat.speciesName = 'Cat'
        /// },
        /// constructor: function() {
        /// var statics = this.statics();
        /// alert(statics.speciesName);     // always equals to 'Cat' no matter what 'this' refers to
        /// // equivalent to: My.Cat.speciesName
        /// alert(this.self.speciesName);   // dependent on 'this'
        /// statics.totalCreated++;
        /// },
        /// clone: function() {
        /// var cloned = new this.self;                      // dependent on 'this'
        /// cloned.groupName = this.statics().speciesName;   // equivalent to: My.Cat.speciesName
        /// return cloned;
        /// }
        /// });
        /// <see cref="Ext.ExtContext.define">Ext.define</see>('My.SnowLeopard', {
        /// extend: 'My.Cat',
        /// statics: {
        /// speciesName: 'Snow Leopard'     // My.SnowLeopard.speciesName = 'Snow Leopard'
        /// },
        /// constructor: function() {
        /// this.callParent();
        /// }
        /// });
        /// var cat = new My.Cat();                 // alerts 'Cat', then alerts 'Cat'
        /// var snowLeopard = new My.SnowLeopard(); // alerts 'Cat', then alerts 'Snow Leopard'
        /// var clone = snowLeopard.clone();
        /// alert(<see cref="Ext.ExtContext.getClassName">Ext.getClassName</see>(clone));         // alerts 'My.SnowLeopard'
        /// alert(clone.groupName);                 // alerts 'Cat'
        /// alert(My.Cat.totalCreated);             // alerts 3
        /// </code>
        /// </summary>
        /// <returns>
        /// <span><see cref="Ext.Class">Ext.Class</see></span><div>
        /// </div>
        /// </returns>
        protected static Class statics(){return null;}
        /// <summary>
        /// Unregisters a Ext.Component from this ZIndexManager. This should not
        /// need to be called. Components are automatically unregistered upon destruction.
        /// See register.
        /// </summary>
        /// <param name="comp"><p>The Component to unregister.</p>
        /// </param>
        public static void unregister(Ext.Component comp){}
        public WindowManager(WindowManagerConfig config){}
        public WindowManager(){}
        public WindowManager(params object[] args){}
    }
    #endregion
    #region WindowManagerConfig
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class WindowManagerConfig : ZIndexManagerConfig
    {
        public WindowManagerConfig(params object[] args){}
    }
    #endregion
    #region WindowManagerEvents
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class WindowManagerEvents : ZIndexManagerEvents
    {
        public WindowManagerEvents(params object[] args){}
    }
    #endregion
}
