//***************************************************
//* This file was generated by tool
//* SharpKit
//* At: 29/08/2012 03:59:42 p.m.
//***************************************************
using SharpKit.JavaScript;
namespace Ext.ux
{
    #region LiveSearchGridPanel
    /// <inheritdocs />
    /// <summary>
    /// <p>A GridPanel class with live search support.</p>
    /// </summary>
    [JsType(JsMode.Prototype, Export=false, OmitOptionalParameters=true)]
    public partial class LiveSearchGridPanel : Ext.grid.Panel
    {
        /// <summary>
        /// The matched string css classe.
        /// Defaults to: <c>&quot;x-livesearch-match&quot;</c>
        /// </summary>
        public JsString matchCls;
        /// <summary>
        /// Case sensitive mode.
        /// Defaults to: <c>false</c>
        /// </summary>
        private bool caseSensitive{get;set;}
        /// <summary>
        /// The row index of the first search, it could change if next or previous buttons are used.
        /// Defaults to: <c>null</c>
        /// </summary>
        private JsObject currentIndex{get;set;}
        /// <summary>
        /// The row indexes where matching strings are found. (used by previous and next buttons)
        /// Defaults to: <c>[]</c>
        /// </summary>
        private JsArray indexes{get;set;}
        /// <summary>
        /// Regular expression mode.
        /// Defaults to: <c>false</c>
        /// </summary>
        private bool regExpMode{get;set;}
        /// <summary>
        /// The generated regular expression used for searching.
        /// Defaults to: <c>null</c>
        /// </summary>
        private JsObject searchRegExp{get;set;}
        /// <summary>
        /// search value initialization
        /// Defaults to: <c>null</c>
        /// </summary>
        private JsObject searchValue{get;set;}
        /// <summary>
        /// Switch to case sensitive mode.
        /// </summary>
        /// <param name="checkbox">
        /// </param>
        /// <param name="checked">
        /// </param>
        private void caseSensitiveToggle(object checkbox, object @checked){}
        /// <summary>
        /// In normal mode it returns the value with protected regexp characters.
        /// In regular expression mode it returns the raw value except if the regexp is invalid.
        /// </summary>
        /// <returns>
        /// <span><see cref="String">String</see></span><div><p>The value to process or null if the textfield value is blank or invalid.</p>
        /// </div>
        /// </returns>
        private JsString getSearchValue(){return null;}
        /// <summary>
        /// Selects the next row containing a match.
        /// </summary>
        private void onNextClick(){}
        /// <summary>
        /// Selects the previous row containing a match.
        /// </summary>
        private void onPreviousClick(){}
        /// <summary>
        /// Finds all strings that matches the searched value in each grid cells.
        /// </summary>
        private void onTextFieldChange(){}
        /// <summary>
        /// Switch to regular expression mode
        /// </summary>
        /// <param name="checkbox">
        /// </param>
        /// <param name="checked">
        /// </param>
        private void regExpToggle(object checkbox, object @checked){}
        public LiveSearchGridPanel(LiveSearchGridPanelConfig config){}
        public LiveSearchGridPanel(){}
        public LiveSearchGridPanel(params object[] args){}
    }
    #endregion
    #region LiveSearchGridPanelConfig
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class LiveSearchGridPanelConfig : Ext.grid.PanelConfig
    {
        /// <summary>
        /// The matched string css classe.
        /// Defaults to: <c>&quot;x-livesearch-match&quot;</c>
        /// </summary>
        public JsString matchCls;
        public LiveSearchGridPanelConfig(params object[] args){}
    }
    #endregion
    #region LiveSearchGridPanelEvents
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class LiveSearchGridPanelEvents : Ext.grid.PanelEvents
    {
        public LiveSearchGridPanelEvents(params object[] args){}
    }
    #endregion
}
