//***************************************************
//* This file was generated by tool
//* SharpKit
//* At: 29/08/2012 03:59:39 p.m.
//***************************************************
using SharpKit.JavaScript;
namespace Ext.chart.theme
{
    #region Base
    /// <inheritdocs />
    /// <summary>
    /// <p><strong>NOTE</strong> This is a private utility class for internal use by the framework. Don't rely on its existence.</p><p>Provides default colors for non-specified things. Should be sub-classed when creating new themes.</p>
    /// </summary>
    [JsType(JsMode.Prototype, Export=false, OmitOptionalParameters=true)]
    public partial class Base : Ext.Base
    {
        public Base(Ext.chart.theme.BaseConfig config){}
        public Base(){}
        public Base(params object[] args){}
    }
    #endregion
    #region BaseConfig
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class BaseConfig : Ext.BaseConfig
    {
        public BaseConfig(params object[] args){}
    }
    #endregion
    #region BaseEvents
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class BaseEvents : Ext.BaseEvents
    {
        public BaseEvents(params object[] args){}
    }
    #endregion
}
