// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.tree
{
    /// <summary>
	/// <para>The tree folder is a tree element, which can have nested tree elements.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.tree.TreeFolder", OmitOptionalParameters = true, Export = false)]
    public partial class TreeFolder : qx.ui.tree.core.AbstractTreeItem
    {
		#region Properties

		/// <summary>
		/// <para>The appearance ID. This ID is used to identify the appearance theme
		/// entry to use for this widget. This controls the styling of the element.</para>
		/// </summary>
		[JsProperty(Name = "appearance", NativeField = true)]
		public string Appearance { get; set; }

		#endregion Properties

		#region Methods

		public TreeFolder() { throw new NotImplementedException(); }

		#endregion Methods
    }
}