//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_.Plugin_
{
    /// <summary>
    /// Plugin for dd-drag for creating a proxy drag node, instead of dragging the original node.
    /// </summary>
    public partial class DDProxy : Y_.Base
    {
    }
}
