//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_.Plugin_
{
    /// <summary>
    /// Handles list manipulation inside the Editor. Adds keyboard manipulation and execCommand support. Adds overrides for the <a href="Plugin.ExecCommand.html#method_COMMANDS.insertorderedlist">insertorderedlist</a> and <a href="Plugin.ExecCommand.html#method_COMMANDS.insertunorderedlist">insertunorderedlist</a> execCommands.
    /// </summary>
    public partial class EditorLists : Y_.Base
    {
        /// <summary>
        /// editorLists
        /// </summary>
        public object NAME{get;set;}
        /// <summary>
        /// The selector query to get all non elements
        /// </summary>
        public object NONSEL{get;set;}
        /// <summary>
        /// lists
        /// </summary>
        public object NS{get;set;}
        /// <summary>
        /// The non element placeholder, used for positioning the cursor and filling empty items
        /// </summary>
        public object REMOVE{get;set;}
    }
}
