//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace Y_.Test_.CoverageFormat_
{
    /// <summary>
    /// An object object containing coverage result formatting methods.
    /// </summary>
    public partial class CoverageFormat
    {
        /// <summary>
        /// Returns the coverage report in JSON format. This is the straight
        /// JSON representation of the native coverage report.
        /// </summary>
        public object JSON(object coverage){return null;}
        /// <summary>
        /// Returns the coverage report in a JSON format compatible with
        /// Xdebug. See <a href="http://www.xdebug.com/docs/code_coverage">Xdebug Documentation</a>
        /// for more information. Note: function coverage is not available
        /// in this format.
        /// </summary>
        public object XdebugJSON(object coverage){return null;}
    }
}
