// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.table.cellrenderer
{
    /// <summary>
	/// <para>The default data cell renderer.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.table.cellrenderer.Default", OmitOptionalParameters = true, Export = false)]
    public partial class Default : qx.ui.table.cellrenderer.Abstract
    {
		#region Properties

		/// <summary>
		/// <para>Whether the alignment should automatically be set according to the cell value.
		/// If true numbers will be right-aligned.</para>
		/// </summary>
		[JsProperty(Name = "useAutoAlign", NativeField = true)]
		public bool UseAutoAlign { get; set; }

		#endregion Properties

		#region Methods

		public Default() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the (computed) value of the property useAutoAlign.</para>
		/// </summary>
		[JsMethod(Name = "getUseAutoAlign")]
		public bool GetUseAutoAlign() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Calls the apply method and dispatches the change event of the property useAutoAlign
		/// with the default value defined by the class developer. This function can
		/// only be called from the constructor of a class.</para>
		/// </summary>
		/// <param name="value">Initial value for property useAutoAlign.</param>
		[JsMethod(Name = "initUseAutoAlign")]
		public void InitUseAutoAlign(object value) { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Check whether the (computed) value of the boolean property useAutoAlign equals true.</para>
		/// </summary>
		[JsMethod(Name = "isUseAutoAlign")]
		public void IsUseAutoAlign() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Resets the user value of the property useAutoAlign.</para>
		/// <para>The computed value falls back to the next available value e.g. appearance, init or
		/// inheritance value depeneding on the property configuration and value availability.</para>
		/// </summary>
		[JsMethod(Name = "resetUseAutoAlign")]
		public void ResetUseAutoAlign() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Sets the user value of the property useAutoAlign.</para>
		/// </summary>
		/// <param name="value">New value for property useAutoAlign.</param>
		[JsMethod(Name = "setUseAutoAlign")]
		public void SetUseAutoAlign(bool value) { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Toggles the (computed) value of the boolean property useAutoAlign.</para>
		/// </summary>
		[JsMethod(Name = "toggleUseAutoAlign")]
		public void ToggleUseAutoAlign() { throw new NotImplementedException(); }

		#endregion Methods
    }
}