// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.eventx.type
{
    /// <summary>
	/// <para>EXPERIMENTAL &#8211; NOT READY FOR PRODUCTION</para>
	/// <para>Swipe event object.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.event.type.Swipe", OmitOptionalParameters = true, Export = false)]
    public partial class Swipe : qx.eventx.type.Touch
    {
		#region Methods

		public Swipe() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns whether the performed swipe was on the x or y axis.</para>
		/// </summary>
		/// <returns>&#8220;x&#8221;/&#8220;y&#8221; axis</returns>
		[JsMethod(Name = "getAxis")]
		public string GetAxis() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the direction of the performed swipe in reference to the axis.
		/// y = up / down
		/// x = left / right</para>
		/// </summary>
		/// <returns>the direction</returns>
		[JsMethod(Name = "getDirection")]
		public string GetDirection() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the distance of the performed swipe.</para>
		/// </summary>
		/// <returns>the distance</returns>
		[JsMethod(Name = "getDistance")]
		public double GetDistance() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the duration the performed swipe took.</para>
		/// </summary>
		/// <returns>the duration</returns>
		[JsMethod(Name = "getDuration")]
		public double GetDuration() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the start time of the performed swipe.</para>
		/// </summary>
		/// <returns>the start time</returns>
		[JsMethod(Name = "getStartTime")]
		public double GetStartTime() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the velocity of the performed swipe.</para>
		/// </summary>
		/// <returns>the velocity</returns>
		[JsMethod(Name = "getVelocity")]
		public double GetVelocity() { throw new NotImplementedException(); }

		#endregion Methods
    }
}